version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - pip install django==3.2.19
      - pip freeze > requirements.txt
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - python3 manage.py test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
